### ISSUE TITLE
Error with MarketIfTouchedOrderRequests for price < 1.0

### ISSUE THREAD

**Issue by mwok** [mrchrisok/OandaV20#1]
Hello. In trying out your C# code I found an error in MarketIfTouchedOrderRequests. See file: RestV20Operations.cs, private static async Task Order_RunOrderOperations(). The code works for MarketIfTouchedOrderRequests if price = 1.0 or greater.  However, "USD_CHF" it is currently trading under 1.0. and the code does not work for values less than 1.0.   For example, if you change instrument to "USD_CHF" (looking up the correct instrument values from GetAccountInstrumentsAsync) and change price to 0.945 then the value 0.945 is incorrectly translated into a request in MakeRequestWithJSONBody. The method, requestBody and requestString are correctly passed into MakeRequestWithJSONBody with the correct value of 0.945 but somehow the 0.945 value is changed back from a string into a number somewhere in the code with a value of 0.94499999999999. Suspect it is changed in the StreamWriter. Or is it when a double precision variable is calculated by Trading algorithm is passed to the Math.Round the round function "does not work" (e.g. Visual Studio 2015 IDE displays the rounded value of 0.945 but real value passed to StreamWriter is 0.94499999999999)  See screen capture error below (note I removed userID, accountID and requestID information).  

![image](https://user-images.githubusercontent.com/35352408/36126625-441a9502-1051-11e8-859d-e577e1012dbc.png)

**Comment by mrchrisok** [comment]
HI mwok,

Thanks for the info. 
Many updates and fixes were implemented in the past few weeks.
It's likely your issue was corrected by this commit:  [ea1c7fd42bc414a9f5d92e1dd83664c6f5f23436](https://github.com/mrchrisok/OandaV20/commit/ea1c7fd42bc414a9f5d92e1dd83664c6f5f23436)
All EntryOrderRequest subtypes are now serialized via PriceObjectConverter.
PriceObjectConverter correctly rounds the instrument price using the instrument displayPrecision.

So, git pull the latest changes.
Let me know if the issue persists.

/oco

**Comment by mwok** [comment]
Hi mrchrisok.  Thanks for the quick reply.  I will download the latest version tonight and give it a try.  Note I used your code from early Feb 2018.  But I did not try the one from 11-Feb-2018 yet.  Will try and see if I have the same problem.

**Comment by mwok** [comment]
Hi mrchirsok. I downloaded your latest code from 12 days ago (about 02-Feb-2018) and there is an error in namespace OkonkwoOandaV20.Framework.Factories   public class ErrorResponseFactory line 14: 
switch (dynamicError.type.ToString())

dynamicError.type.ToString() is underlined and the error message is: "A switch expression or case label must be a bool, char, string, integral, enum, or corresponding nullable type

**Comment by mrchrisok** [comment]
Mwok,

The dev environment for OkonkwoOandaV20 was upgraded to VS2017 and C#7 late last year. C#7 introduced improvements and new capabilities for the switch statement including additional types and pattern matching. A terrific summary article is here (https://www.google.com/url?sa=t&source=web&rct=j&url=http://www.c-sharpcorner.com/article/c-sharp-7-0-and-c-sharp-7-1-new-features-part-two/&ved=2ahUKEwjqntqD_6PZAhWEt1MKHSWSDFgQFjAHegQIBRAB&usg=AOvVaw0PEMmhNVMtIgcIlNABf8eg).

So, a fix for you is to upgrade your environment to VS2017/C#7.  Another is to set a string variable for dynamicError.type.ToString() then use the string variable in the switch.

/oco

**Comment by mwok** [comment]
Mrchrisok, 

Thanks for the tips, help and quick responses.  I will upgrade to VS2017 / C#7, migrate my VS2015 code files over to a fresh build and try it again with the switch not bypassed.
Cheers!
M
