### ISSUE TITLE
alternative to quoteHomeConversionFactors?

### ISSUE THREAD

**Issue by bigmiguel** [mrchrisok/OandaV20#11]
Hi,

is more a question than a issue, i want to use the quoteHomeConversionFactors property of the price class but will by obsolete and get me a error, which property i can use instead of this?

**Comment by mrchrisok** [comment]
Hi bigmiguel,

Obsolete properties and behavior should not be used for new builds.
quoteHomeConversionFactors was already deprecated by Oanda prior to the creation of the OandaV20 library.
As such, it was most responsible to configure the library to raise a build error for any usage of the property.
It's inclusion was only to ensure that the library completely reflected all properties and behavior of the Oanda api.
