### ISSUE TITLE
example of creating market order with stoploss and take profit

### ISSUE THREAD

**Issue by hoangdungt2** [mrchrisok/OandaV20#15]
Hi,

Recently I started to use your package and it's very helpful. And I'm trying to create a MarketOrder with Stoploss and Takeprofit but I cannot find any example. I mainly use F# and cannot quite understand your source code of the `EntryOrderRequest` and `ExitOrderRequest`, do help. thanks

**Comment by ghost** [comment]
Note that those classes inherit other classes.  That might help you understand them by looking at the child classes.

**Comment by hoangdungt2** [comment]
Just notice when creating `MarketOrderRequest` I can use `takeProfitOnFill` and `stopLossOnFill` for stoploss and tp information. thanks
