### ISSUE TITLE
multiple instance

### ISSUE THREAD

**Issue by magellancl** [mrchrisok/OandaV20#16]
Hello,

I need to be able to connect multiple users asynchronously to pass orders, each with a different Oanda token, is there any way to create separated instance and define credentials for each one ?

Thank you

**Comment by mrchrisok** [comment]
OANDAV20.1 is no longer supported
The final version is 1.0.6935.1917
OANDAV20.2 is available here: https://github.com/mrchrisok/OandaV20.2
