### ISSUE TITLE
Error in Rest20.GetOrderListAsync when passing List<string> orderIDs

### ISSUE THREAD

**Issue by mwok** [mrchrisok/OandaV20#2]
Hello Mrchirsok.  I have upgraded to VS2017, ported everything into a fresh new VS2017 project and all Switches seem to be fixed. I was testing your code and found an issue with Rest20.GetOrderListAsync when passing List<string> orderIDs.  I wrote the simple code below to test passing both the List<string> orderIDs and Dictionary<string, string> requestParams.  The Dictionary works fine and it returned all orders with instrument = "AUD_JPY".  However, when passed a short list of 5 valid MARKET_IF_TOUCHED order ID numbers as strings the following error message is returned: Invalid value specified for "ids", "type":"ErrorResponse"

                    // get list of pending orders
                    var AcctPendingOrders = await Rest20.GetPendingOrderListAsync(AccountId);  //These are all orders

                    int ICount = 0;
                    var OrderMIfTouchIDList = new List<string>();
                    foreach (var a1 in AcctPendingOrders)
                    {
                        if (a1 != null && a1.type == "MARKET_IF_TOUCHED")
                        {
                            var IDNum = a1.id;
                            var IDString = Convert.ToString(IDNum);
                            OrderMIfTouchIDList.Add(IDString);
                            ICount = ICount + 1;
                            if (ICount >= 5) break;
                        }
                    }
                    var ParamsDict = new Dictionary<string, string>
                    {
                        { "instrument", "AUD_JPY" }
                    };

                    // get list of open orders which are "MARKET_IF_TOUCHED" orders
                    var AcctOrders = await Rest20.GetOrderListAsync(AccountId, OrderMIfTouchIDList, null); //This returns sub-set of orders using List of orderIDs
                    //var AcctOrders = await Rest20.GetOrderListAsync(AccountId, null, ParamsDict); // //This returns sub-set of orders using Dictionary values

**Comment by mrchrisok** [comment]
Mwok,

Thanks for the find. 
The error occurs due to escaping the orderIDs list before forming the query string for the /orders call.
This behavior was previously untested.
I've removed the call to Ur.EscapeDataString since it's not needed for the 'ids' csv.
I've also added  condition 11.29 to test_Order_get_all_orders to test the retrieval of orders when passing the List<string> orderIDs parameter to GetOrderListAsync.

Chris

**Comment by mwok** [comment]
Thanks for the fast reply and for taking time to update the code and fixing the bug.  I re-tested your latest code from 19-Feb-2018 with a List orderIDs, Dictionary and even both at the same time.  Passing ether Dictionary and List orderIDs parameters or even both at the same time to GetOrderListAsync work well.  Nice fix!
