### ISSUE TITLE
GetOrderListAsync only returns 50 orders

### ISSUE THREAD

**Issue by mwok** [mrchrisok/OandaV20#4]
Hello Chris.  I have a large number of Orders in my test account (e.g. 91 orders).  I was testing your code and comparing the output of GetOrderListAsync to GetPendingOrderListAsync.  It seems that GetOrderListAsync only returns a maximum List size of 50 where as GetPendingOrderListAsync returns all of the pending orders (e.g. 91 orders in my case).  I am not sure if you intended to return only 50 orders in GetOrderListAsync.  If so this could be a simple "documentation" fix to state that GetOrderListAsync is limited to 50 orders in the Summary information header above GetOrderListAsync.  Note: I could not find where in the code GetOrderListAsync was being limited to 50.  This maybe on the Oanda side.  Not sure.  This is not a high priority issue and can wait to be addressed later combined with some other issues.  Hope my comments are helpful...
Regards,
Mike

**Comment by mrchrisok** [comment]
Mwok,

The GetOrderListAsync method targets the Oanda v20 /orders  [endpoint ](http://developer.oanda.com/rest-live-v20/order-ep/). The  /orders endpoint returns only 50 orders by default for each GET request. The maximum number that can be returned from a  single request is 500. To specify the number of orders returned from /orders, add a 'count' parameter to the Dictionary<string,string> passed to the GetOrderListAsync method. 

That said, a future enhancement for the OandaV20 project will be to replace the Dictionary<string,string> parameters with typed parameter objects with properties that correspond to the Oanda endpoint parameters for each operation.  Until then, you will find it a terrific investment to spend an hour or two reviewing the Oanda V20 endpoint [documentation](http://developer.oanda.com/rest-live-v20/introduction/), best practices and release notes to become more familiar with its capabilities.

Chris

**Comment by mwok** [comment]
Chris -
Thanks for the quick response, the tips and clarification on the use of GetOrderListAsync and the count parameter.
Regards,
Mike
