### ISSUE TITLE
Rest20 using static classes to get credentials

### ISSUE THREAD

**Issue by ersingencturk** [mrchrisok/OandaV20#6]
This needs to be changed with instance classes.Is there a special reason why you had them as static classes ?

**Comment by mrchrisok** [comment]
Turk,

Oanda V20 accounts offers subaccounts tied to a primary account.
Only 1 access token is needed to make calls to the primary or sub accounts.
All calls to Oanda via OandaV20 have an 'account' parameter.
The account value supplied can be the primary account or a subaccount.
The 'DefaultAccountId' property of the Credentials class can be used to optionally cache a default account to be used for calls.

Chris

**Comment by ersingencturk** [comment]
maybe you should have a look at the official java sdk and how they have implemented.

https://github.com/oanda/v20-java/blob/master/src/com/oanda/v20/Context.java

**Comment by mrchrisok** [comment]
Turk,

If the Java implementation better suits your needs, it's imminently sensible that you should use it. 

Chris
