### ISSUE TITLE
Source code licence

### ISSUE THREAD

**Issue by mfow** [mrchrisok/OandaV20#7]
Hi,

Very useful project!

What is the licence this project is distributed under?

**Comment by mrchrisok** [comment]
Hi mfow,

Like soo many other OS projects, I wrote this project for myself really.
I needed a quality C# dll for a OandaV20 and didn't find one.
Along the way as I wrote this one, adding a license document was utterly overlooked.
I've now added an MIT license.

Thanks for the prompt,
/oco
